# Generated by Django 3.2.4 on 2021-07-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
    ]
