# Generated by Django 3.2.4 on 2021-07-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_comment_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
