# Generated by Django 3.2.4 on 2021-07-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
