# Generated by Django 3.2.4 on 2021-07-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
