# Generated by Django 3.2.4 on 2021-07-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210706_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
